server:
  port: 8087
  servlet:
    context-path: /api/authorization
management:
  server:
    port: 8187
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: auth #authorization
    change-log: db/changelog/auth/db.changelog-master.yaml
    enabled: true
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: auth
    application:
      name: authorization-app

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.web: DEBUG
      org.springframework.security.authentication: DEBUG
      org.springframework.security.core: DEBUG
      com.bank.authorization: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
